using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Bytes.Sound;

public class PlayerController : MonoBehaviour
{
    private GrappleHook grappleScript;
    private CharacterMovement movementScript;
    private Rigidbody rb;
    [SerializeField] SoundPlayer soundPlayer;
    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        grappleScript = GetComponent<GrappleHook>();
        movementScript = GetComponent<CharacterMovement>();
        soundPlayer = GetComponent<SoundPlayer>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void Stun(float duration){
        grappleScript.Stun(duration);
        movementScript.Stun(duration);
        soundPlayer.PlaySound("PlayerHurt");
    }

    public void Knockback(Vector2 dir){
        soundPlayer.PlaySound("PlayerKnockback");
        rb.AddForce(dir);
    }
}
